### PR TITLE
Update hub.json to add dbt-uaparser

### PR DESCRIPTION
**Pull request by andrewcstewart**
Adds https://github.com/andrewcstewart/dbt-uaparser to hub.json

### CODE REVIEW

**Review by dbeatty10 — APPROVED** [review]
Cool @andrewcstewart 😎 !

I'm approving this now, and a placeholder will go up on the dbt package Hub within the next hour.

But no installable packages will show up until you have at least one tag in a format like "0.1.0" [here](https://github.com/andrewcstewart/dbt-uaparser/tags).

**Comment by dbeatty10** [comment]
I _thought_ there would be a placeholder on [hub.getdbt.com](https://hub.getdbt.com/), but it looks like nothing will show up until you make your first version tag on your project.

From there, hopefully it will be automatically displayed on [hub.getdbt.com](https://hub.getdbt.com/) within 1.5 hours after you make the tag. If not, then let me know and I will troubleshoot.

**Comment by andrewcstewart** [comment]
Done!  Thanks @dbeatty10

**Comment by andrewcstewart** [comment]
@dbeatty10 it's up!  The only problem now is that I seem to have won the Alphabetical Order contest!   This is far too much pressure!  We need to solicit the data engineering team at https://aaa.com/ or something to publish some packages to bump me out of 1st.  😁 

image

**Pull request merged**
