### PR TITLE
Add Matatika/dbt-tap-solarvista to hub

### PR DESCRIPTION
**Pull request by aphethean1**
Please consider our dbt package for the hub.  Thanks.

### CODE REVIEW

**Comment by aphethean1** [comment]
Hi @jtcohen6 - do I need to do anything further for you to be able to review our request?

**Comment by VersusFacit** [comment]
Hi there, let's get you merged. Just would like to know what your testing routine was to make sure models make sense. Did your environment variable setup treat you well? We tend to recommend using property files (.yml) to let variables set those variables but an environment variable is alright as well!

**Comment by aphethean1** [comment]
Hi @VersusFacit - we developed these models for various clients and a daily automated import task in our platform.  This daily task sets up a workspace from scratch, which is backed by a Meltano project in a new git repo, these models are then added to the meltano project and tested with 'dbt test' followed by an SIT which checks data is return to the charts.  Our platform together with Meltano manages the setting of the required environment variables for the target schema.

(Sorry for the delayed reply!)

**Comment by aphethean1** [comment]
Hi @VersusFacit did that explain how we developed and tested the models?  Anything else you need to get this published?

**Comment by aphethean1** [comment]
Hi @jtcohen6 @VersusFacit - perhaps you are busy with Coalesce.  Just wondering if you have an update on publishing our models?

**Comment by aphethean1** [comment]
@jtcohen6 @VersusFacit hello.  Do you have any update for us?

**Comment by joellabes** [comment]
@aphethean1 sorry for the delay here! Same comment as on the [other PR](https://github.com/dbt-labs/hubcap/pull/85#issuecomment-995407771) - as @VersusFacit said, env vars are non-traditional but as long as they work for your customers then that's OK by us. Potentially in the future you'll want to change them to be sources so that they fully participate in the dbt DAG.

**Comment by joellabes** [comment]
I've committed the new package [separately](https://github.com/dbt-labs/hubcap/commit/cdda3937f910e71cc7592198625ff26cbbe47b2e), so I'll close this now 👍

**Comment by aphethean1** [comment]
Thanks @joellabes - and thank you for the recommendation.  We'll make those changes in the next release.

**Pull request closed without merging**
