### PR TITLE
Rename dbtvault to AutomateDV

### PR DESCRIPTION
**Pull request by DVAlexHiggs**
Update dbtvault to AutomateDV for rebrand
No other changes otherwise

Corresponding hub.getdbt.com PR: https://github.com/dbt-labs/hub.getdbt.com/pull/2470

### CODE REVIEW

**Review by dbeatty10 — APPROVED** [review]
Sounds good @DVAlexHiggs 👍

**Comment by dbeatty10** [comment]
@DVAlexHiggs I realized after the fact that this needed to be reverted in #260 -- sorry I didn't notice this earlier!

Which name(s) are you hoping to replace? There's two options:
1. dbt package name
1. GitHub repo name

These are not mutually exclusive -- you could choose to do both.

The instructions below are assuming you only want to update the dbt package name. Let me know if you want to do something different than that, and I can explain renaming the GitHub repo.

### Renaming a dbt package

In the Hub website, it will display the name from [this](https://github.com/Datavault-UK/dbtvault/blob/4ce2cfbd8c17fb33ea95ae65b52c193a73ec45e5/dbt_project.yml#L1) line. It is also the name that will be used when calling a macro like this:
```sql
{{ dbtvault.hub(src_pk, src_nk, src_ldts, src_source, source_model) }}
```

This name MAY have underscores, but it MUST NOT have dashes.

So either of these would be valid dbt package names:
- `automatedv`
- `automate_dv`

But this would not:
- `automate-dv`

### Renaming a dbt package on hub.getdbt.com

Here's an example of a package rename:
1. https://github.com/elementary-data/dbt-data-reliability/commit/e4d837d16a86a3da5c209bcb45751249ba331d45
2. https://github.com/dbt-labs/hub.getdbt.com/pull/1461/files

**Comment by DVAlexHiggs** [comment]
> @DVAlexHiggs I realized after the fact that this needed to be reverted in #260 -- sorry I didn't notice this earlier!
> 
> Which name(s) are you hoping to replace? There's two options:
> 
> 1. dbt package name
> 2. GitHub repo name
> 
> These are not mutually exclusive -- you could choose to do both.
> 
> The instructions below are assuming you only want to update the dbt package name. Let me know if you want to do something different than that, and I can explain renaming the GitHub repo.
> 
> ### Renaming a dbt package
> In the Hub website, it will display the name from [this](https://github.com/Datavault-UK/dbtvault/blob/4ce2cfbd8c17fb33ea95ae65b52c193a73ec45e5/dbt_project.yml#L1) line. It is also the name that will be used when calling a macro like this:
> 
> ```sql
> {{ dbtvault.hub(src_pk, src_nk, src_ldts, src_source, source_model) }}
> ```
> 
> This name MAY have underscores, but it MUST NOT have dashes.
> 
> So either of these would be valid dbt package names:
> 
> * `automatedv`
> * `automate_dv`
> 
> But this would not:
> 
> * `automate-dv`
> 
> ### Renaming a dbt package on hub.getdbt.com
> Here's an example of a package rename:
> 
> 1. [elementary-data/dbt-data-reliability@e4d837d](https://github.com/elementary-data/dbt-data-reliability/commit/e4d837d16a86a3da5c209bcb45751249ba331d45)
> 2. https://github.com/dbt-labs/hub.getdbt.com/pull/1461/files

Thanks for this. 

We do want to do both:

1. Rename the GitHub repository to: `automate-dv` 
2. Rename the package to `automate_dv`


So, the way I understand it for 1, I need to of course rename the repository, and then add a redirectname to the `index.json` over on hub.getdbt.com.

For 2, update the `dbt_project.yml` in the main repo?

Thanks

**Comment by dbeatty10** [comment]
@DVAlexHiggs https://github.com/dbt-labs/hub.getdbt.com/pull/2470 is merged and deployed now so it's back down to a single package --  please reach out if you notice anything else unaddressed.

image

Anyone that has a [legacy URL](https://hub.getdbt.com/datavault-uk/dbtvault/latest/) will see this message:

image

**Comment by DVAlexHiggs** [comment]
@dbeatty10 Thanks very much! Appreciate the assistance

**Pull request merged**
