### PR TITLE
feat: add dbt-graph-theory package

### PR DESCRIPTION
**Pull request by jpmmcneill**
## Description 

Package to deal help when data you are dealing with can be modelled as a graph.

https://github.com/jpmmcneill/dbt-graph-theory

Examples of such things:
- events
- history tables

## Checklist
This checklist is a cut down version of the [best practices](package-best-practices.md) that we have identified as the package hub has grown. Although meeting these checklist items is not a prerequisite to being added to the Hub, we have found that packages which don't conform provide a worse user experience. 

### First run experience
- [x] The package includes a README which explains how to get started with the package and customise its behaviour
- [x] The README indicates which data warehouses/platforms are expected to work with this package

### Customisability
- [x] The package uses ref or source, instead of hard-coding table references.

#### Dependencies on dbt Core
- [x] The package has set a supported `require-dbt-version` range in `dbt_project.yml`. Example: A package which depends on functionality added in dbt Core 1.2 should set its `require-dbt-version` property to `[">=1.2.0", "<2.0.0"]`.
#### Dependencies on other packages defined in packages.yml:
- [x] Dependencies are imported from the dbt Package Hub when available, as opposed to a git installation.
- [x] Dependencies contain the widest possible range of supported versions, to minimise issues in dependency resolution.
- [x] In particular, dependencies are not pinned to a patch version unless there is a known incompatibility.
### Interoperability
- [x] The package does not override dbt Core behaviour in such a way as to impact other dbt resources (models, tests, etc) not provided by the package.
- [x] The package uses the cross-database macros built into dbt Core where available, such as `{{ dbt.except() }}` and `{{ dbt.type_string() }}`.
- [x] The package disambiguates its resource names to avoid clashes with nodes that are likely to already exist in a project. For example, packages should not provide a model simply called `users`.

### Versioning
- [x] (Required): The package's git tags validates against the regex defined in [version.py](/hubcap/version.py)
- [x] The package's version follows the guidance of Semantic Versioning 2.0.0. (Note in particular the recommendation for production-ready packages to be version 1.0.0 or above)

### CODE REVIEW

**Review by dbeatty10 — APPROVED** [review]
Nice @jpmmcneill ! 🤩

Been looking forward to this since you first mentioned it was in the works.

Note: After approving and merging, I need to take a manual action for it to be live on [hub.getdbt.com](https://hub.getdbt.com/). If it's not live in about an hour, could you ping me? That would mean I either forgot to take the manual action or ran into some other issue during re-deployment.

**Comment by jpmmcneill** [comment]
> Nice @jpmmcneill ! 🤩
> 
> Been looking forward to this since you first mentioned it was in the works.
> 
> Note: After approving and merging, I need to take a manual action for it to be live on [hub.getdbt.com](https://hub.getdbt.com/). If it's not live in about an hour, could you ping me? That would mean I either forgot to take the manual action or ran into some other issue during re-deployment.

Will do @dbeatty10, thank you!

**Comment by jpmmcneill** [comment]
Hey @dbeatty10 fyi I'm not able to see it on the hub atm

**Comment by jpmmcneill** [comment]
Ah I see this caused an exception (sorry 😇). Possibly these are related

**Comment by dbeatty10** [comment]
No worries @jpmmcneill -- you didn't do anything wrong.

### Explanation

Although [hub.getdbt.com](https://hub.getdbt.com/) can display and serve prerelease tags like [1.0.0-rc1](https://github.com/dbt-labs/dbt-utils/releases/tag/1.0.0-rc1) (see [here](https://hub.getdbt.com/dbt-labs/dbt_utils/1.0.0-rc1/)), it can't currently handle the situation where there are _only_ prereleases and aren't any final versions yet.

So since your only tag right now is [0.1.0-b1](https://github.com/jpmmcneill/dbt-graph-theory/releases/tag/0.1.0-b1), it wouldn't deploy it to hub.getdbt.com.

### Next steps
If and when you publish a final tag like `0.1.0`, then we can get it working for hub.getdbt.com. As of right now, we won't be able to add your package until then.

Separately, I've got a draft PR https://github.com/dbt-labs/hubcap/pull/229 that would allow this to work in the future.

**Comment by jpmmcneill** [comment]
Thanks @dbeatty10 , there were only a few small things (possibly allready solved - I can't remember) that I wanted to do before releasing a non beta version.

I'll follow up here when 0.1.0 is released.

On a separate note, is there a standard dbt like when it comes to version tags having the "v" prefix? I've seen packages doing both (eg. Fivetran have "v"s)

**Comment by jpmmcneill** [comment]
Hey @dbeatty10 - FYI there are now two releases, `0.1.0` and `0.1.0-b1`.

**Comment by dbeatty10** [comment]
> Hey @dbeatty10 - FYI there are now two releases, `0.1.0` and `0.1.0-b1`.

Awesome! We'll see if it works in about an hour.

> On a separate note, is there a standard dbt like when it comes to version tags having the "v" prefix? I've seen packages doing both (eg. Fivetran have "v"s)

Both with and without "v"s are allowed in the tag names. If there is a "v" prefix in the git tag, we'll just strip it off before determining if the remainder is valid according to the [SemVer 2.0 spec](https://semver.org/spec/v2.0.0.html#is-v123-a-semantic-version).

**Comment by dbeatty10** [comment]
@jpmmcneill Your package is live 🎉 

https://hub.getdbt.com/jpmmcneill/dbt_graph_theory/latest/

**Comment by jpmmcneill** [comment]
Wooo! Thanks @dbeatty10 😄

**Pull request merged**
