### PR TITLE
Re-re-add BfdCampos/source_db

### PR DESCRIPTION
**Pull request by joellabes**
third time's the charm, as they say

## Description 

Concluding the saga from #289 and #280 

Link to your package's repository: https://github.com/BfdCampos/source_db

### CODE REVIEW

**Comment by joellabes** [comment]
@BfdCampos bad news - the 0.1.0 tag still exists even though you deleted the release, which means that Hubcap is still running into the same issue as before :( 

can you delete the tag please?

**Comment by joellabes** [comment]
Now that you have deleted the release, you should be able to delete the tag from this page https://github.com/BfdCampos/source_db/tags


image

**Comment by BfdCampos** [comment]
@joellabes I feel like this probably holds the record as to how many times something has been added and reverted to this repo. If anything I guess, I have that...

image

Deleted now! Should be ok(?) 🤞

**Comment by BfdCampos** [comment]
@joellabes You think fourth time's the one? 🤞 I think everything is there this time 😓

**Comment by joellabes** [comment]
Victoryyyyy! https://hub.getdbt.com/BfdCampos/source_db/latest/

Thanks for sticking through it 🎉

**Comment by BfdCampos** [comment]
What a journey it has been. It's been an honour serving with you @joellabes 🫡

**Pull request merged**
