### PR TITLE
update hub.json

### PR DESCRIPTION
**Pull request by thutuva**
Added 2 packages and updated the repository name for 1:
2 packages added:  tuva_chronic_conditions and pmpm
1 package updated:  chronic_conditions to cms_chronic_conditions (still the same repository in Github as previously but renamed)

## Description 

Tell us about your new package! 
We are adding 2 new packages:
1.  tuva_chronic_conditions creates chronic conditions flags based on cohorts and logic we created internally at Tuva
2. pmpm calculates and provides the per member/per month cost of healthcare for a patient based on their claims data

I have also updated the name of 1 existing package:
1.  chronic_conditions is now cms_chronic_conditions.  The repository is the same as before but has been renamed.  Since we are releasing our own version of the chronic conditions logic we need to different/specify the package that contains the CMS logic.

## Checklist
This checklist is a cut down version of the [best practices](package-best-practices.md) that we have identified as the package hub has grown. Although meeting these checklist items is not a prerequisite to being added to the Hub, we have found that packages which don't conform provide a worse user experience. 

### First run experience
- [x] The package includes a README which explains how to get started with the package and customise its behaviour
- [x] The README indicates which data warehouses/platforms are expected to work with this package

### Customisability
- [x] The package uses ref or source, instead of hard-coding table references.
#### Packages for data transformation (delete if not relevant):
- [x] provide a mechanism (such as variables) to customise the location of source tables.
- [x] do not assume database/schema names in sources.

#### Dependencies on dbt Core
- [ ] The package has set a supported `require-dbt-version` range in `dbt_project.yml`. Example: A package which depends on functionality added in dbt Core 1.2 should set its `require-dbt-version` property to `[">=1.2.0", "<2.0.0"]`.
#### Dependencies on other packages defined in packages.yml:
- [x] Dependencies are imported from the dbt Package Hub when available, as opposed to a git installation.
- [x] Dependencies contain the widest possible range of supported versions, to minimise issues in dependency resolution.
- [x] In particular, dependencies are not pinned to a patch version unless there is a known incompatibility.
### Interoperability
- [x] The package does not override dbt Core behaviour in such a way as to impact other dbt resources (models, tests, etc) not provided by the package.
- [x] The package uses the cross-database macros built into dbt Core where available, such as `{{ dbt.except() }}` and `{{ dbt.type_string() }}`.
- [x] The package disambiguates its resource names to avoid clashes with nodes that are likely to already exist in a project. For example, packages should not provide a model simply called `users`.

### Versioning
- [x] (Required): The package's git tags validates against the regex defined in [version.py](/hubcap/version.py)
- [x] The package's version follows the guidance of Semantic Versioning 2.0.0. (Note in particular the recommendation for production-ready packages to be version 1.0.0 or above)

### CODE REVIEW

**Review by dbeatty10 — APPROVED** [review]
I'm approving this shortly, which will add the new packages to the Hub.

The "old" `chronic_conditions` will still show up until we do some things on our end to "archive" it.

Once I do the steps on our end, the Hub will re-route anybody that still has `chronic_conditions` listed in their packages.yml to the renamed `cms_chronic_conditions` package instead.

**Comment by thutuva** [comment]
Thanks, Doug!  Happy Holidays!

**Comment by dbeatty10** [comment]
Happy Holidays @thutuva !

image

I'll let you know once the "archive" step is completed for `chronic_conditions`.

**Comment by dbeatty10** [comment]
✅ "Archive" step is done. This completes the rename from `chronic_conditions` to `cms_chronic_conditions `.

Before:
image

After:
image

**Pull request merged**
