### PR TITLE
Added Datomni/profitwell_metrics and Datomni/ga4_metrics packages

### PR DESCRIPTION
**Pull request by enikovarga**
## Description 

[profitwell_metrics](https://github.com/Datomni/profitwell_metrics): this package provides daily and monthly metrics based on data generated by Profitwell. The package is compatible with BigQuery.

[ga4_metrics](https://github.com/Datomni/ga4_metrics): this dbt package sessionizes the ga4 dataset and creates a set of traffic metrics based on the sessions.

## Checklist
This checklist is a cut down version of the [best practices](package-best-practices.md) that we have identified as the package hub has grown. Although meeting these checklist items is not a prerequisite to being added to the Hub, we have found that packages which don't conform provide a worse user experience. 

### First run experience
- [x] The package includes a README which explains how to get started with the package and customise its behaviour
- [x] The README indicates which data warehouses/platforms are expected to work with this package

### Customisability
- [x] The package uses ref or source, instead of hard-coding table references.
#### Packages for data transformation (delete if not relevant):
- [x] provide a mechanism (such as variables) to customise the location of source tables.
- [x] do not assume database/schema names in sources.

#### Dependencies on dbt Core
- [x] The package has set a supported `require-dbt-version` range in `dbt_project.yml`. Example: A package which depends on functionality added in dbt Core 1.2 should set its `require-dbt-version` property to `[">=1.2.0", "<2.0.0"]`.
#### Dependencies on other packages defined in packages.yml:
- [x] Dependencies are imported from the dbt Package Hub when available, as opposed to a git installation.
- [x] Dependencies contain the widest possible range of supported versions, to minimise issues in dependency resolution.
- [x] In particular, dependencies are not pinned to a patch version unless there is a known incompatibility.
### Interoperability
- [x] The package does not override dbt Core behaviour in such a way as to impact other dbt resources (models, tests, etc) not provided by the package.
- [ ] The package uses the cross-database macros built into dbt Core where available, such as `{{ dbt.except() }}` and `{{ dbt.type_string() }}`.
- [x] The package disambiguates its resource names to avoid clashes with nodes that are likely to already exist in a project. For example, packages should not provide a model simply called `users`.

### Versioning
- [x] (Required): The package's git tags validates against the regex defined in [version.py](/hubcap/version.py)
- [x] The package's version follows the guidance of Semantic Versioning 2.0.0. (Note in particular the recommendation for production-ready packages to be version 1.0.0 or above)

### CODE REVIEW

**Review by dbeatty10 — CHANGES_REQUESTED** [review]
Cool @enikovarga !

Could you explicitly specify `require-dbt-version` within `dbt_project.yml`? When this is specified, then dbt can proactively verify version compatibility when users install your package.

The relevant docs are [here](https://docs.getdbt.com/reference/project-configs/require-dbt-version), and [here](https://github.com/jpmmcneill/dbt-graph-theory/blob/c22353b1ff9e5c454e632ce15687d0521f3880b5/dbt_project.yml#L4) is a real-world example.

You can also specify only a lower bound without an upper bound if you want:
`require-dbt-version: ">=0.13.0"`

**Comment by enikovarga** [comment]
@dbeatty10 thanks for the review! The `require-dbt-version` is now specified in the `dbt_project.yml` file.

**Comment by dbeatty10** [comment]
@joellabes would you be available to take a look at this PR? If not, you can send it back to me.

See description for links to each package repo in GitHub.

**Review by joellabes — APPROVED** [review]
thank you @enikovarga and @dbeatty10!

**Pull request merged**
