### PR TITLE
Add fhir-dbt-analytics package

### PR DESCRIPTION
**Pull request by jakubadamek**
## Description 

Data quality analytics for FHIR exported to BigQuery.

## Checklist
This checklist is a cut down version of the [best practices](package-best-practices.md) that we have identified as the package hub has grown. Although meeting these checklist items is not a prerequisite to being added to the Hub, we have found that packages which don't conform provide a worse user experience. 

### First run experience
- [x] The package includes a README which explains how to get started with the package and customise its behaviour
- [x] The README indicates which data warehouses/platforms are expected to work with this package

### Customisability
- [x] The package uses ref or source, instead of hard-coding table references.
#### Packages for data transformation (delete if not relevant):
- [x] provide a mechanism (such as variables) to customise the location of source tables.
- [x] do not assume database/schema names in sources.

#### Dependencies on dbt Core
- [ ] The package has set a supported `require-dbt-version` range in `dbt_project.yml`. Example: A package which depends on functionality added in dbt Core 1.2 should set its `require-dbt-version` property to `[">=1.2.0", "<2.0.0"]`.
#### Dependencies on other packages defined in packages.yml:
- [x] Dependencies are imported from the dbt Package Hub when available, as opposed to a git installation.
- [ ] Dependencies contain the widest possible range of supported versions, to minimise issues in dependency resolution.
- [x] In particular, dependencies are not pinned to a patch version unless there is a known incompatibility.
### Interoperability
- [x] The package does not override dbt Core behaviour in such a way as to impact other dbt resources (models, tests, etc) not provided by the package.
- [ ] The package uses the cross-database macros built into dbt Core where available, such as `{{ dbt.except() }}` and `{{ dbt.type_string() }}`.
- [ ] The package disambiguates its resource names to avoid clashes with nodes that are likely to already exist in a project. For example, packages should not provide a model simply called `users`.

### Versioning
- [x] (Required): The package's git tags validates against the regex defined in [version.py](/hubcap/version.py)
- [x] The package's version follows the guidance of Semantic Versioning 2.0.0. (Note in particular the recommendation for production-ready packages to be version 1.0.0 or above)

### CODE REVIEW

**Review by joellabes — APPROVED** [review]
@jakubadamek Thanks for submitting this! A couple of non-blocking comments: 

- Because you're pinned to specific patch versions of [dbt_expectations and dbt_unittest](https://github.com/google/fhir-dbt-analytics/blob/856445a15a9b010be2dae97c7a93d7d965790b5a/packages.yml#L16-L19), you may find that your users run into conflicts if they specify a different patch inside the same minor version. 
- Your readme specifies dbt Core v1.2 or above, but that's not defined in `require-dbt-version` in `dbt_project.yml`. 
- It's not out of the question that some users might already have a model called [metric](https://github.com/google/fhir-dbt-analytics/blob/856445a15a9b010be2dae97c7a93d7d965790b5a/models/post_processing/metric.sql) (for example), so you might find that users have a clash here. 

And a clarifying question for me - the readme specifies that it needs to be on dbt Core, is it incompatible with Cloud in some way or have you just not provided instructions for dbt Cloud? 

Welcome to the Hub!

**Comment by jakubadamek** [comment]
Thanks a lot, Joe! I already fixed require-dbt-version and will fix the patch versions straight away. 
We will see if we want to rename `metric` and perhaps other models.
As to dbt Cloud - it's just the latter.

**Comment by jakubadamek** [comment]
Would you like to merge this PR now, Joe? Thanks!

**Comment by joellabes** [comment]
Yes that's perfect, thanks so much @jakubadamek!

**Pull request merged**
