### PR TITLE
Added Github DBT package for Airbyte

### PR DESCRIPTION
**Pull request by milo157**
Added a DBT package for the Github connector on DBT

### CODE REVIEW

**Review by dbeatty10 — APPROVED** [review]

**Comment by dbeatty10** [comment]
Looks good @milo157 !

One comment: best not to pin your utils dependency to 0.8.4 in [packages.yml](https://github.com/CerebriumAI/airbyte_dbt_github/blob/e5b73f52dab7552b52ff1d243d2b2c97c3f48ce2/packages.yml#L3) - it should be any 0.8.x version so `version: [">=0.8.0", "<0.9.0"]` instead.

It will show up on [hub.getdbt.com](https://hub.getdbt.com/) after our next release of that website.

**Comment by dbeatty10** [comment]
You're up on hub.getdbt.com now:
https://hub.getdbt.com/cerebriumai/

**Comment by milo157** [comment]
Awesome! Thanks @dbeatty10! Quick question, if I change the package name in the main repo will it automatically update?

**Comment by dbeatty10** [comment]
If you change the package name, it will automatically create a new entry on hub.getdbt.com.

Then I'll do a linkage behind the scenes so that it hides the old name. Anyone that uses the old name will be automatically re-directed to the new name.

I'm guessing you're asking because these are the same (just old name vs. new)?
image

**Comment by milo157** [comment]
Correct. If you can remove the plain GitHub name. The latest should be airbyte_github

Thank you!

**Comment by dbeatty10** [comment]
✅ Done!

Thanks for reaching out about this so we could get it all squared away.

**Pull request merged**
